# Generated by Django 5.1.7 on 2025-03-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('word_count', models.IntegerField(default=0)),
                ('richness_score', models.FloatField(default=0)),
                ('relevance_score', models.FloatField(default=0)),
                ('grammar_score', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
            ],
        ),
    ]
