# Generated by Django 5.1.7 on 2025-03-23 04:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essay',
            name='grammar_score',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='relevance_score',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='title',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='total_score',
        ),
        migrations.AddField(
            model_name='essay',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
