# Generated by Django 5.1.7 on 2025-03-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0002_remove_essay_grammar_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='required_word_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='essay',
            name='richness_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='essay',
            name='topic',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='essay',
            name='word_count_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='essay',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
