# Generated by Django 5.1.7 on 2025-05-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradedEssay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_text', models.TextField()),
                ('word_count', models.IntegerField()),
                ('required_word_count', models.IntegerField()),
                ('topic', models.CharField(max_length=255)),
                ('word_count_marks', models.FloatField()),
                ('word_richness_marks', models.FloatField()),
                ('relevance_marks', models.FloatField()),
                ('spelling_marks', models.FloatField()),
                ('grammar_marks', models.FloatField()),
                ('total_marks', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
